import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  jobs: defineTable({
    company: v.string(),
    title: v.string(),
    location: v.string(),
    skills: v.array(v.string()),
    experienceLevel: v.string(),
    description: v.string(),
    publicId: v.optional(v.string()),
    externalId: v.optional(v.string()),
    platform: v.optional(v.string()),
    workMode: v.optional(v.string()),
    jobUrl: v.optional(v.string()),
    applicationLink: v.optional(v.string()),
    applyUrl: v.optional(v.string()),
    highlights: v.optional(v.array(v.string())),
    summary: v.optional(v.string()),
    requirements: v.optional(v.string()),
    jobType: v.optional(v.string()),
    employmentType: v.optional(v.string()),
    seniorityLevel: v.optional(v.string()),
    isRemote: v.optional(v.boolean()),
    minYearsExperience: v.optional(v.number()),
    maxYearsExperience: v.optional(v.number()),
    salaryRange: v.optional(v.string()),
    minSalary: v.optional(v.number()),
    maxSalary: v.optional(v.number()),
    latitude: v.optional(v.number()),
    longitude: v.optional(v.number()),
    sectorTags: v.optional(v.array(v.string())),
    isExternal: v.optional(v.boolean()),
    postedDate: v.optional(v.string()),
    scrapedAt: v.optional(v.string()),
    isActive: v.optional(v.boolean()),
    extraData: v.optional(v.any()),
    embedding: v.optional(v.array(v.number())),
  })
    .index("by_public_id", ["publicId"])
    .index("by_external_id", ["externalId"]),

  applicants: defineTable({
    publicId: v.string(),
    name: v.string(),
    targetRoles: v.array(v.string()),
    skills: v.array(v.string()),
    resumeText: v.string(),
    location: v.string(),
    remote: v.boolean(),
    experienceYears: v.number(),
    education: v.string(),
    availability: v.string(),
    projects: v.array(v.string()),
    evidenceLines: v.array(v.string()),
    profileStory: v.string(),
    embedding: v.optional(v.array(v.number())),
    embeddingModel: v.optional(v.string()),
    embeddingVersion: v.optional(v.string()),
    sourceKind: v.optional(v.string()),
    sourceId: v.optional(v.string()),
    sourceUrl: v.optional(v.string()),
    sourcePage: v.optional(v.number()),
    sourceChecksum: v.optional(v.string()),
  }).index("by_public_id", ["publicId"]),

  recruiters: defineTable({
    publicId: v.string(),
    company: v.string(),
    roleToHire: v.string(),
    prioritySkills: v.array(v.string()),
    niceToHave: v.array(v.string()),
    story: v.string(),
    location: v.string(),
    workMode: v.string(),
    interviewFocus: v.array(v.string()),
    name: v.optional(v.string()),
    isExample: v.optional(v.boolean()),
    sourceKind: v.optional(v.string()),
  }).index("by_public_id", ["publicId"]),

  sessions: defineTable({
    sessionId: v.string(),
    role: v.union(v.literal("applicant"), v.literal("recruiter")),
    personaId: v.string(),
    selectedMatchId: v.optional(v.string()),
    recentQuery: v.optional(v.string()),
    lastRunId: v.optional(v.string()),
    lastMatchIds: v.array(v.string()),
    updatedAt: v.number(),
  })
    .index("by_session_id", ["sessionId"])
    .index("by_role_and_persona_id", ["role", "personaId"]),

  runLogs: defineTable({
    runId: v.string(),
    role: v.union(v.literal("applicant"), v.literal("recruiter")),
    personaId: v.string(),
    sessionId: v.string(),
    agentType: v.string(),
    action: v.string(),
    message: v.string(),
    payloadJson: v.optional(v.string()),
    timestamp: v.number(),
  })
    .index("by_run_id", ["runId"])
    .index("by_role_and_persona_id", ["role", "personaId"]),
});
